### ISSUE TITLE
`spec.policy.resolution` set to Optional is not honoured for label selectors

### ISSUE THREAD

**Issue by Samze** [crossplane-contrib/function-environment-configs#12]
### What happened?

It seems that `spec.policy.resolution` set to Optional only applies for EnvironmentConfigs who are selected directly by Reference but does not work for Selectors.

### How can we reproduce it?

Create an input to a reference for an EnvironmentConfig that does not exist.
I had an input like this:
```yaml
  - step: loadEnvironmentConfigs
    functionRef:
      name: function-environment-configs
    input:
      apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        policy:
          resolution: Optional
        environmentConfigs:
          - type: Selector
            selector:
              matchLabels:
              - key: foo
                type: FromCompositeFieldPath
                valueFromFieldPath: metadata.name
```

You see the following error in my XR.
```
   message: 'cannot compose resources: pipeline step "loadEnvironmentConfigs" returned
        a fatal result: cannot get selected environment configs: expected exactly
        one extra resource "environment-config-0", got 0'
```

I believe this is because the [guard](https://github.com/crossplane-contrib/function-environment-configs/blob/main/fn.go#L144) is only being applied in the reference case. 

### What environment did it happen in?
Function version: 0.0.4

**Comment by phisco** [comment]
This is because by reference we mean what in the list of selected EnvironmentConfigs previously saved at `spec.environmentConfigRefs`. So optional means: if it got referenced but is not there anymore, ignore it. But with selectors you have one step before, you have to select what gets in that list first and we decided to error out in the default mode (single) if more or less than one exact match is found, while multiple mode allows selecting the first k matches or erroring out if not enough matches are found.

I know it's convoluted 😅 we should definitely improve this API, but rn we focused on porting the exact upstream API.

**Comment by Samze** [comment]
Gotcha, thanks for the quick response. Setting this worked in my selector:
```yaml
          mode: Multiple
          maxMatch: 1
          minMatch: 0
```
