### ISSUE TITLE
Array Envs -- Not Merged Envs

### ISSUE THREAD

**Issue by reedjosh** [crossplane-contrib/function-environment-configs#20]
### What problem are you facing?
I would really like to select envs and then be able to create an object for each env I find.

Currently each env I find gets merged which necessitates a unique starting node for each env I want to create.

So for k8s cluster I'd do something like:
envconfig for cluster1
``` yaml
cluster1:
    data:
       all the things
```

``` yaml
envconfig for cluster2
cluster2:
    data:
       all the things 
```

Purely to make each node unique.

### How could this Function help solve your problem?
If this function could fill an array of all found envconfigs then I could range over them in a go template function or similar.

So maybe optionally we could enable an additional key indexable like `index .context "apiextensions.crossplane.io/environments"`
