### ISSUE TITLE
Allow getting EnvironmentConfig references from claims

### ISSUE THREAD

**Issue by tomaszkiewicz** [crossplane-contrib/function-environment-configs#40]
### What problem are you facing?

Currently, there's no way to dynamically specify environment configs to use. I'd like user creating claim to be able to specify environment name or selector and then propagate it to the function, so it can then select the environment.

Eg. we create a composition with something like that:

```yaml
      functionRef:
           name: function-environment-configs
        input:
           apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
           kind: Input
           spec:
              environmentConfigs:
                 - type: ClaimPath
                   refPath: .spec.environmentName
```

Then user can create a claim:

```yaml
....
spec:
  environmentName: dev
```

And then the function can read that field and load proper environment.
The same logic would apply to the selector, so user can specify selector in the claim, and then we propagate it to the function.
