### ISSUE TITLE
`crossplane render` does not work with this function

### ISSUE THREAD

**Issue by MichelJansen91** [crossplane-contrib/function-environment-configs#53]
### What happened?

Crossplane render command does not seem to work when using this function

### How can we reproduce it?

1. Take https://github.com/upbound/composition-testing/tree/main/crossplane-cli/render/extra_resources as basis
2. Migrate Environment config from v1alpha1 to v1beta1 (are located`extraresources/resources.yaml`)
3. Add `function-environment-configs` function to `functions.yaml`
4. Add following snippet to the composition:
```
    - step: from-environment
      functionRef:
        name: function-environment-configs
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
          - type: Reference
            ref:
              name: webdev-dev
```
5. Try to render with:
```
crossplane render \                                                                                            128 х  4s  07:37:47
  --extra-resources extra-resources \
  --include-full-xr \
  --include-context \
  xr.yaml composition.yaml functions.yaml
```

Then you will get:

> crossplane: error: cannot render composite resource: pipeline step "from-environment" returned a fatal result: cannot get selected environment configs: Required environment config "environment-config-0" not found

### What environment did it happen in?
Function version: v0.1.0
Crossplane version v1.18.0 running locally on MacOS Sequoia
